### ISSUE TITLE
Permission Denied On Login

### ISSUE THREAD

**Issue by waxnet** [dev-bittu/mitmproxy-in-termux#1]
Im getting a permission denied error when using the command "proot-distro login ubuntu"

realpath: /linkerconfig/ld.config.txt: Permission denied

**Comment by dev-bittu** [comment]
Attach screenshot.

**Comment by waxnet** [comment]
![SmartSelect_20240321_092952_Termux](https://github.com/dev-bittu/mitmproxy-in-termux/assets/88239635/d06210fe-5bbd-4745-8323-df4f9dec3375)

**Comment by dev-bittu** [comment]
I will make video on this topic and then send you today. Wait for it...

**Comment by cyberkernelofficial** [comment]
watch this: https://youtu.be/CMi-MkwCloY
and if you encounter further errors, please comment below.

OR

Contact us on Telegram: https://t.me/cyberkernelofficial

**Comment by waxnet** [comment]
> watch this: https://youtu.be/CMi-MkwCloY and if you encounter further errors, please comment below.
> 
> OR
> 
> Contact us on Telegram: https://t.me/cyberkernelofficial

This worked for me thank you very much

**Comment by cyberkernelofficial** [comment]
Most welcome :)

**Comment by waxnet** [comment]
Alr everything works the only problem is that the certificate doesnt seem to work or it has not installed properly, I've tried installing them on Android and on Termux but I still get handshake errors.

![SmartSelect_20240322_080749_Termux](https://github.com/cyberkernelofficial/mitmproxy-in-termux/assets/88239635/80b7c996-7c4a-4b49-8332-6e2a6253a4aa)

**Comment by cyberkernelofficial** [comment]
In the second part of the video; we will explore this : )

**Comment by cyberkernelofficial** [comment]
Hey, we finally uploaded video. Check it out:
https://youtu.be/o-iypVqI_P8
